### ISSUE TITLE
Needs review

### ISSUE THREAD

**Issue by hexylena** [TAMU-CPT/galaxy-apollo-docs#1]
cc @monicacecilia @nathandunn if y'all have comments / changes please feel free to PR them. I took a stab at removing things specific to my org, but .. the docs are probably missing a _lot_

**Comment by monicacecilia** [comment]
Thanks for putting these together. Yes, I'll check. 
You rawk, @erasche!! :bowtie:

**Comment by nathandunn** [comment]
I did a quick perusal.  

There were some header issues (they weren’t highlighted, e.g., Main Panel)) in here (https://github.com/TAMU-CPT/galaxy-apollo-docs/blob/master/doc/Galaxy.rst https://github.com/TAMU-CPT/galaxy-apollo-docs/blob/master/doc/Galaxy.rst), but I’m not sure if they’ll be processed in differently in readthedocs.org  though.

Nathan

**Comment by hexylena** [comment]
I'm not sure what you mean, header issue? main panel?

**Comment by nathandunn** [comment]
Super-minor . . . I just figured you'd rather be on the side of having too much feedback.  Otherwise I agree with @monicacecilia  . . . looks awesome. 

![screen shot 2016-05-27 at 3 20 22 pm](https://cloud.githubusercontent.com/assets/751274/15622547/96f0be44-241e-11e6-8c38-88b30ba482bf.png)

**Comment by hexylena** [comment]
Aha! Nice catches, thank you.
